{
    "editor.stickyScroll.enabled": false,
    "security.workspace.trust.untrustedFiles": "open",
    "editor.hideCursorInOverviewRuler": true,
    "diffEditor.experimental.useTrueInlineView": true,
    "editor.suggest.preview": true,
    "workbench.view.alwaysShowHeaderActions": true,
    "workbench.editor.enablePreviewFromCodeNavigation": true,
    "workbench.editor.enablePreviewFromQuickOpen": true,
    "workbench.editor.sharedViewState": true,
    "accessibility.hideAccessibleView": true,
    "debug.showBreakpointsInOverviewRuler": true,
    "testing.automaticallyOpenPeekViewDuringAutoRun": true,
    "extensions.closeExtensionDetailsOnViewChange": true,
    "terminal.integrated.accessibleViewFocusOnCommandExecution": true,
    "terminal.integrated.accessibleViewPreserveCursorPosition": true,
    "notebook.diff.overviewRuler": true,
    "notebook.variablesView": true,
    "debug.javascript.enableNetworkView": true,
    "markdown.preview.typographer": true,
    "mediaPreview.video.autoPlay": true,
    "mediaPreview.video.loop": true,
    "tabnine.experimentalAutoImports": true,
    "workbench.statusBar.visible": false,
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "code-runner.runInTerminal": true,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.editor.empty.hint": "hidden",
    "workbench.colorTheme": "Visual Studio 2017 Dark - C++",
    "files.autoSave": "afterDelay",
    "git.openRepositoryInParentFolders": "never",
    "editor.quickSuggestions": {
        
        "other": "offWhenInlineCompletions",
        "comments": "off",
        "strings": "off"
    }
}